[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=Xvfb :0 -screen 0 1280x800x24
autorestart=true
priority=100

[program:openbox]
command=openbox
environment=DISPLAY=":0"
autorestart=true
priority=200

[program:x11vnc]
command=x11vnc -display :0 -nopw -forever -shared -rfbport 5900 -listen 127.0.0.1
autorestart=true
priority=300

[program:novnc]
command=websockify --web /usr/share/novnc 8080 127.0.0.1:5900
autorestart=true
priority=400

[program:fazpos]
command=/app/fazpos
environment=DISPLAY=":0",SLINT_BACKEND="winit"
autorestart=true
priority=500
directory=/app
